### ISSUE TITLE
TODOLIST  7 Aug - 13 Aug 2017

### ISSUE THREAD

**Issue by jibalio** [lerycibalio/msa-mis#2]
# TODO LIST  7 Aug - 13 Aug 2017
## Frontend @AJPasigado 
- [x] Walay new line ang RylMessageBox UI sa katong pag click sa Save sa adjustment
- [x] Hide adjust button if payroll is approved
- [x] Prompts in exiting forms
- [x] Payroll Quick Glance Information
- [x] rates editor (simple)
- [x] Archive Form Design
- [x] SSS Payroll Popup
- [x] Payroll Status (Approve, Pending, Paid)
- [x] Connect public DataTable GetAdjustmentHistory()
      `columns: adjtype, addedon, value`
## Back-end  @lerycibalio 
- [ ] Figure out how to solve the "multiple client contracts in 1 period" payroll problem. (or check if i already fixed this lmao)
- [ ] If wlay trabaho dont put sweldo k?
- [ ] Remember to remove contrib_id in rates *optional*
- [ ] Payroll showing blank assignments for approved request without assignment 
- [ ] ARCHIVEEEE
- [ ] **Payroll.GetPreviousPayday() <-- NEW!**
- [x] Status Column (Dismissal - Unassignment) Assigned Guards List in Duty Details
- [x] GetIncidentReportsDetails(RID)
- [x] Function body for SetRates.
- [x] Check on Program startup for active / inactief guards
- [x] Rates multiplier
- [x] Configure of Payroll status
- [x] Change -1 for ending dates in Basic Pay Rates 
- [x] Store calculated fields of old payrolls in database
- [x] Save serialized objects to db (for approved payrolls)
- [x] Set assignment status to active only on ass. activation date.
- [x] Set guard status to active once contract starts.
- [x] Remove guard status once contract expires.
- [x] Check on startup: expired & new rates (de)
# Reports & DataVal @rhyleregodon 
- [ ] Payslip generation
- [ ] Salary Report generation
- [ ] Duty Details generation
- [x] RylUI Message Boxes returning wrong DialogResult

**Comment by AJPasigado** [comment]
Wait akoa na ning the rest?

**Comment by jibalio** [comment]
ako ana xD, dili nako ma tag akong self for some reason
